import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { loadCatalog, listPacks, listProfiles, catalogStats } from './catalog.mjs';
import { loadAllSkills } from './skill-loader.mjs';
import { isInside, resolveUnderRoot } from './paths.mjs';

const SECRET_PATTERNS = [
  /\bsk-[A-Za-z0-9_-]{8,}\b/g,
  /\bghp_[A-Za-z0-9]{20,}\b/g,
  /\bgithub_pat_[A-Za-z0-9_]{20,}\b/g,
  /\bAKIA[0-9A-Z]{16}\b/g,
  /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g,
  /\bAIza[0-9A-Za-z_-]{20,}\b/g
];

export function redactSecrets(text) {
  let out = String(text ?? '');
  for (const pattern of SECRET_PATTERNS) {
    out = out.replace(pattern, '[REDACTED]');
  }
  return out;
}

export async function exportAgentsMd(root, options = {}) {
  const repoRoot = resolve(root);
  let outPath;
  try {
    outPath = options.out
      ? resolveUnderRoot(repoRoot, options.out, { allowAbsolute: options.allowAbsolute === true })
      : join(repoRoot, 'AGENTS.md');
  } catch (error) {
    return { ok: false, error: error.message, path: null };
  }
  if (!isInside(repoRoot, outPath) && outPath !== join(repoRoot, 'AGENTS.md')) {
    if (!options.allowAbsolute) {
      return { ok: false, error: `out path escapes repository root: ${outPath}`, path: null };
    }
  }

  let catalogSection = '';
  try {
    const { catalog } = await loadCatalog(root);
    const stats = catalogStats(catalog);
    const packs = listPacks(catalog);
    const profiles = listProfiles(catalog);
    catalogSection = [
      `SkillsForge catalog: **${stats.skills}** catalog entries, **${stats.packs}** packs, **${stats.profiles}** profiles.`,
      '',
      'Hero depth: trust spine + lifecycle + methodology skills are production-depth; domain packs are lean scaffolds.',
      '',
      '### Profiles',
      ...profiles.map((p) => `- \`${p.id}\`: ${p.description} (packs: ${p.packs.join(', ')})`),
      '',
      '### Packs',
      ...packs.map((p) => `- \`${p.id}\` (${p.skillCount}): ${p.description}`)
    ].join('\n');
  } catch (error) {
    catalogSection = `Catalog unavailable: ${error.message}`;
  }

  const skills = await loadAllSkills(root);
  const agentsDir = join(root, 'plugins', 'skillsforge', 'agents');
  let agents = [];
  try {
    agents = (await readdir(agentsDir)).filter((name) => name.endsWith('.md'));
  } catch {
    agents = [];
  }

  const content = `# AGENTS.md

Generated by \`skillsforge export-agents\`. Cross-harness context for Claude Code, Cursor, Codex, and OpenCode.

## SkillsForge

Use SkillsForge as the trust and routing layer for Agent Skills.

- Magical moment: \`npx skillsforge vibe\`
- Judge demo: \`npx skillsforge demo\`
- Validate: \`skillsforge validate --all\`
- Route: \`skillsforge route --query "..."\` or \`--pack <id>\`
- Quality: \`skillsforge quality --skill <dir>\`
- Evidence: \`skillsforge evidence --out artifacts/evidence\`

## Catalog

${catalogSection}

## Installed skills (sample)

${skills.slice(0, 40).map((s) => `- \`${s.name}\` — ${(s.description ?? '').slice(0, 120)}`).join('\n')}
${skills.length > 40 ? `\n… and ${skills.length - 40} more.\n` : '\n'}

## Agents

${agents.length ? agents.map((name) => `- \`plugins/skillsforge/agents/${name}\``).join('\n') : '_No agent defs yet._'}

## Complementary tools

- Use Ruflo for multi-agent swarm orchestration if needed; SkillsForge does not clone swarm/MCP consensus.
- Use SkillsForge for validate, forge, route, policy, package, and evidence.

## Skill routing (short)

When the request matches a SkillsForge skill, invoke it. Prefer pack-scoped routing for domain skills (\`routing.mode: explicit\`).
`;

  if (!options.dryRun) {
    await writeFile(outPath, content);
  }
  return { ok: true, path: outPath, skills: skills.length, agents: agents.length, dryRun: Boolean(options.dryRun) };
}

export async function captureLearning(root, entry) {
  const repoRoot = resolve(root);
  const outDir = join(repoRoot, 'artifacts', 'capture');
  if (!isInside(repoRoot, outDir)) {
    return { ok: false, error: 'capture directory escapes repository root' };
  }
  await mkdir(outDir, { recursive: true });
  const redacted = {
    ts: new Date().toISOString(),
    ...entry,
    insight: entry.insight != null ? redactSecrets(entry.insight) : undefined,
    summary: entry.summary != null ? redactSecrets(entry.summary) : undefined,
    key: entry.key != null ? redactSecrets(String(entry.key)) : undefined
  };
  const line = JSON.stringify(redacted);
  const path = join(outDir, 'learnings.jsonl');
  let existing = '';
  try {
    existing = await readFile(path, 'utf8');
  } catch {
    existing = '';
  }
  await writeFile(path, `${existing}${line}\n`);

  const learningMd = join(repoRoot, 'docs', 'work', 'learning.md');
  if (!isInside(repoRoot, learningMd)) {
    return { ok: false, error: 'learning.md path escapes repository root' };
  }
  await mkdir(join(repoRoot, 'docs', 'work'), { recursive: true });
  let md = '';
  try {
    md = await readFile(learningMd, 'utf8');
  } catch {
    md = '# learning\n\n';
  }
  md += `\n- ${redacted.insight ?? redacted.summary ?? JSON.stringify(redacted)}\n`;
  await writeFile(learningMd, md);
  return { ok: true, path, learningMd };
}

export async function forgeFromCapture(root, options = {}) {
  const path = join(resolve(root), 'artifacts', 'capture', 'learnings.jsonl');
  let raw = '';
  try {
    raw = await readFile(path, 'utf8');
  } catch {
    return { ok: false, error: 'no capture file' };
  }
  const lines = raw.trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
  const counts = new Map();
  for (const row of lines) {
    const key = (row.key ?? row.insight ?? row.summary ?? '').toString().slice(0, 80);
    if (!key) continue;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  const candidates = [...counts.entries()]
    .filter(([, n]) => n >= (options.minCount ?? 2))
    .sort((a, b) => b[1] - a[1])
    .slice(0, options.limit ?? 5)
    .map(([key, count]) => ({
      key,
      count,
      suggestedName: key.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'captured-skill',
      note: 'Human must approve before forge --write'
    }));
  return { ok: true, candidates };
}
