import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

export const POWERSHELL_HELPERS = Object.freeze([
  {
    name: 'sf-status',
    description: 'Compact repo and SkillsForge status',
    args: ['wb', 'status', '--json']
  },
  {
    name: 'sf-tree',
    description: 'Compact file tree',
    args: ['wb', 'tree']
  },
  {
    name: 'sf-find',
    description: 'Token-friendly file finder',
    args: ['wb', 'find']
  },
  {
    name: 'sf-grep',
    description: 'Token-friendly ripgrep wrapper',
    args: ['wb', 'grep']
  },
  {
    name: 'sf-diff',
    description: 'Compact git diff summary',
    args: ['wb', 'diff']
  },
  {
    name: 'sf-errors',
    description: 'Find likely error and TODO markers',
    args: ['wb', 'errors']
  },
  {
    name: 'sf-bigfiles',
    description: 'List largest repo files',
    args: ['wb', 'bigfiles']
  },
  {
    name: 'sf-recent',
    description: 'Recent git commits',
    args: ['wb', 'recent']
  },
  {
    name: 'sf-ports',
    description: 'Listening port snapshot',
    args: ['os-ports']
  },
  {
    name: 'sf-proof',
    description: 'Trust proof command hints',
    args: ['wb', 'proof', '--json']
  }
]);

export async function exportPowerShellHelpers(root, options = {}) {
  const outDir = resolve(root, options.outDir ?? join('artifacts', 'powershell'));
  const cliPath = resolve(root, 'plugins', 'skillsforge', 'bin', 'skillsforge.mjs');
  await mkdir(outDir, { recursive: true });
  const files = [];
  for (const helper of POWERSHELL_HELPERS) {
    const path = join(outDir, `${helper.name}.ps1`);
    await writeFile(path, renderHelper(helper, cliPath));
    files.push({ name: helper.name, path, description: helper.description });
  }
  const manifest = {
    ok: true,
    generatedAt: new Date().toISOString(),
    cli: cliPath,
    helpers: files
  };
  await writeFile(join(outDir, 'skillsforge-powershell.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return { ok: true, outDir, files, manifest: join(outDir, 'skillsforge-powershell.json') };
}

function renderHelper(helper, cliPath) {
  const baseArgs = helper.args.map((arg) => `'${escapeSingle(arg)}'`).join(', ');
  return `# ${helper.description}
# Generated by skillsforge ps export.
param(
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]] $Args
)

$SfCli = '${escapeSingle(cliPath)}'
$BaseArgs = @(${baseArgs})
& node $SfCli @BaseArgs @Args
exit $LASTEXITCODE
`;
}

function escapeSingle(value) {
  return String(value).replaceAll("'", "''");
}
