import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const modulePath = fileURLToPath(import.meta.url);
const repositoryRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const schemaDirectory = join(repositoryRoot, 'schemas');
const defaultOutput = join(repositoryRoot, 'scripts', 'schemas.generated.mjs');
const suffix = '.schema.json';

export async function renderSchemasModule() {
  const files = (await readdir(schemaDirectory, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith(suffix))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const schemas = {};
  for (const file of files) {
    const key = basename(file, suffix);
    schemas[key] = JSON.parse(await readFile(join(schemaDirectory, file), 'utf8'));
  }

  const serialized = JSON.stringify(schemas, null, 2);
  return `// Generated by scripts/gen-schemas.mjs. Do not edit by hand.\n\nexport const schemas = Object.freeze(${serialized});\n\nexport const skillSchemasByProfile = Object.freeze({\n  canonical: schemas['skill.frontmatter'],\n  'claude-code': schemas['claude-code.frontmatter']\n});\n`;
}

export async function generateSchemasModule(output = defaultOutput) {
  const source = await renderSchemasModule();
  await writeFile(output, source, 'utf8');
  return { output, source };
}

if (process.argv[1] && resolve(process.argv[1]) === modulePath) {
  const output = process.argv[2] ? resolve(process.argv[2]) : defaultOutput;
  await generateSchemasModule(output);
  console.log(`Generated ${output}`);
}
